<?php
    $cn=new mysqli("localhost","root","","TIENDA");    
    /*
    CREATE DATABASE TIENDA;
    USE TIENDA;
    CREATE TABLE CLIENTES(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
     NOMBRE VARCHAR(20),
      APELLIDO_P VARCHAR(30),
       APELLIDO_M VARCHAR(30),
        TELEFONO VARCHAR(30),
         CORREO VARCHAR(30) UNIQUE,
          CONTRASEÑA VARCHAR(15));

    CREATE TABLE COMIDAS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
     NOMBRE VARCHAR(20) UNIQUE,
      PRECIO FLOAT,
       TIPO VARCHAR(10),
        DISPONIBILIDAD BOOLEAN);
    
    CREATE TABLE PUESTOS (
     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
      NOMBRE_PUESTO VARCHAR(20) UNIQUE,
       PAGO_EXTRA FLOAT);

    CREATE TABLE COCINEROS (
     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
      NOMBRE VARCHAR(20),
       APELLIDO VARCHAR(30),
        ID_PUESTO INTEGER,
         EDAD INTEGER,
          ESPECIALIDAD VARCHAR(10),
           FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS(ID));

    
    CREATE TABLE FACTURA (
     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
      ID_CLIENTE INTEGER,
       ID_COMIDA INTEGER,
        ID_COCINERO INTEGER,
         ID_PUESTO INTEGER,
          TOTAL FLOAT,
           PAGADO BOOLEAN,
            FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
             FOREIGN KEY (ID_COMIDA) REFERENCES COMIDAS(ID),
              FOREIGN KEY (ID_COCINERO) REFERENCES COCINEROS(ID),
               FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS(ID));

    INSERT INTO COMIDAS VALUES (NULL,'GORDITAS',45.5,'MEXICANA',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'TACOS',50.9,'MEXICANA',FALSE);
    INSERT INTO COMIDAS VALUES (NULL,'PAMBAZO',15,'MEXICANA',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'POZOLE',35,'MEXICANA',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'SOPES',15,'MEXICANA',FALSE);
    INSERT INTO COMIDAS VALUES (NULL,'ESPAGETI',60,'ITALIANA',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'BRUSCHETTA',100,'ITALIANA',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'OSSOBUCO',80,'ITALIANA',FALSE);
    INSERT INTO COMIDAS VALUES (NULL,'RISOTTO',50,'ITALIANA',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'PIZZA',60,'ITALIANA',TRUE);

    INSERT INTO COMIDAS VALUES (NULL,'CHOCOFLAN',20,'POSTRES',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'ARROZ_CON_LECHE',10,'POSTRES',FALSE);
    INSERT INTO COMIDAS VALUES (NULL,'PASTEL',50,'POSTRES',FALSE);
    INSERT INTO COMIDAS VALUES (NULL,'GELATINA',15,'POSTRES',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'PAY_DE_LIMON',80,'POSTRES',FALSE);
    

    INSERT INTO COMIDAS VALUES (NULL,'AGUA_SIMPLE',10,'BEBIDAS',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'REFRESCO',30,'BEBIDAS',FALSE);
    INSERT INTO COMIDAS VALUES (NULL,'CAFE',25,'BEBIDAS',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'VICTORIA',35,'BEBIDAS',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'LIMONADA',5,'BEBIDAS',FALSE);

    INSERT INTO COMIDAS VALUES (NULL,'COCTEL',50,'MARISCOS',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'CEVICHE',40,'MARISCOS',TRUE);
    INSERT INTO COMIDAS VALUES (NULL,'MOJARRA',80,'MARISCOS',FALSE);
    INSERT INTO COMIDAS VALUES (NULL,'CAMARON',55,'MARISCOS',FALSE);
    INSERT INTO COMIDAS VALUES (NULL,'TRUCHA',60,'MARISCOS',TRUE);

    
    INSERT INTO PUESTOS VALUES(NULL,'CHEF',50);
    INSERT INTO PUESTOS VALUES(NULL,'REPOSTERO',10);
    INSERT INTO PUESTOS VALUES(NULL,'BARMAN',10);



    INSERT INTO COCINEROS VALUES(NULL,'KIRBY','KIRBY',1,99,'MEXICANA');
    INSERT INTO COCINEROS VALUES(NULL,'MARIO','BROS',1,99,'ITALIANA');
    INSERT INTO COCINEROS VALUES(NULL,'COMEGALLETAS','RIOS',2,99,'POSTRES');
    INSERT INTO COCINEROS VALUES(NULL,'MIGUEL','CORREA',3,99,'BEBIDAS');
    INSERT INTO COCINEROS VALUES(NULL,'MANOLO','CRUZ',1,99,'MARISCOS');



    INSERT INTO COCINEROS VALUES(NULL,'Juan', 'Pérez', 1, 35, 'MEXICANA');
    INSERT INTO COCINEROS VALUES(NULL, 'Luis', 'Ramírez', 1, 38, 'MEXICANA');

    INSERT INTO COCINEROS VALUES(NULL,'María', 'Gómez', 2, 28, 'ITALIANA');
    INSERT INTO COCINEROS VALUES(NULL, 'Laura', 'Fernández', 2, 30, 'ITALIANA');

    INSERT INTO COCINEROS VALUES(NULL,'Carlos', 'López', 3, 40, 'POSTRES');
    INSERT INTO COCINEROS VALUES(NULL, 'Javier', 'García', 3, 42, 'POSTRES');

    INSERT INTO COCINEROS VALUES(NULL,'Ana', 'Martínez', 1, 32, 'BEBIDAS');
    INSERT INTO COCINEROS VALUES(NULL,'MIGUEL','CORREA',3,99,'BEBIDAS');
    
    INSERT INTO COCINEROS VALUES(NULL,'Pedro', 'Sánchez', 2, 25, 'MARISCOS');
    INSERT INTO COCINEROS VALUES(NULL, 'Elena', 'Rodríguez', 1, 29, 'MARISCOS');
    */
?>